### ISSUE TITLE
Why call Routing.init() in the start method of App class ?

### ISSUE THREAD

**Issue by jifffffy** [rjaros/kvision-realworld-example-app-fullstack#1]
Hi, I am leraning the fullstack project. I do not understand why called Routing.init() method!

**Comment by rjaros** [comment]
The `init()` method is used to initialize default `routing` instance. It can take different parameters. 
Please check: https://kvision.gitbook.io/kvision-guide/3.-optional-ui-functionality-via-modules/js-routing

**Comment by jifffffy** [comment]
Yes, I see. but the project  seem to  use the `routing` is  `private val routing = Navigo(null, true, "#")` in the  `ConduitManager` class to add route .

**Comment by rjaros** [comment]
Yes, I think you are correct. The default instance is not used in this project and the `Routing.init()` call should not be required. It's probably left by an oversight.
